/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrabajoInterfaces;

import TrabajoInterfaces.Usuarios.Perfil;
import TrabajoInterfaces.Usuarios.Usuarios;
import TrabajoInterfaces.Usuarios.Roles;
import TrabajoInterfaces.Informes.InformesPlantillas;
import TrabajoInterfaces.Informes.Informes;
import TrabajoInterfaces.Vehiculos.CrearVehiculo;
import TrabajoInterfaces.Vehiculos.ModificarVehiculo;
import TrabajoInterfaces.Vehiculos.PlantillasVehiculo;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nestor.fernandez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Princ
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));
        setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N

        jDesktopPane1.setBackground(new java.awt.Color(232, 229, 224));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(18, 54, 69));
        jMenuBar1.setForeground(new java.awt.Color(204, 0, 51));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenuBar1.setFocusable(false);

        jMenu1.setBackground(new java.awt.Color(18, 54, 69));
        jMenu1.setForeground(new java.awt.Color(245, 243, 241));
        jMenu1.setText("Usuarios");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEnteredMenu1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExitedMenu1(evt);
            }
        });

        jMenuItem1.setText("Perfil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilClick(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Control de Usuarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosClick(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Roles");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolesClick(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(18, 54, 69));
        jMenu2.setForeground(new java.awt.Color(245, 243, 241));
        jMenu2.setText("Informes");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEnteredMenu2(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExitedMenu2(evt);
            }
        });

        jMenuItem5.setText("Generar Informe");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformesClick(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("Plantillas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantillasClick(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 51, 51));
        jMenu3.setForeground(new java.awt.Color(245, 243, 241));
        jMenu3.setText("Vehículos");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEnteredMenu3(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExitedMenu3(evt);
            }
        });

        jMenuItem6.setText("Crear Vehículo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearVehiculoClick(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem10.setText("Modificar Vehículo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarVehiculoClick(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem7.setText("Plantillas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehiculoPlantillasClick(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(18, 54, 69));
        jMenu4.setForeground(new java.awt.Color(245, 243, 241));
        jMenu4.setText("Rutas");
        jMenu4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEnteredMenu4(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExitedMenu4(evt);
            }
        });

        jMenuItem8.setText("Crear Ruta");
        jMenu4.add(jMenuItem8);

        jMenuItem11.setText("Modificar Ruta");
        jMenu4.add(jMenuItem11);

        jMenuItem9.setText("Plantillas");
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MouseEnteredMenu1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEnteredMenu1
        // TODO add your handling code here:
        jMenu1.setForeground(Color.decode("#dd6d10"));
    }//GEN-LAST:event_MouseEnteredMenu1

    private void MouseEnteredMenu2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEnteredMenu2
        // TODO add your handling code here:
        jMenu2.setForeground(Color.decode("#dd6d10"));
    }//GEN-LAST:event_MouseEnteredMenu2

    private void MouseEnteredMenu3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEnteredMenu3
        // TODO add your handling code here:
        jMenu3.setForeground(Color.decode("#dd6d10"));
    }//GEN-LAST:event_MouseEnteredMenu3

    private void MouseEnteredMenu4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEnteredMenu4
        // TODO add your handling code here:
        jMenu4.setForeground(Color.decode("#dd6d10"));
    }//GEN-LAST:event_MouseEnteredMenu4

    private void MouseExitedMenu1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseExitedMenu1
        // TODO add your handling code here:
        jMenu1.setForeground(Color.decode("#f5f3f1"));
    }//GEN-LAST:event_MouseExitedMenu1

    private void MouseExitedMenu2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseExitedMenu2
        // TODO add your handling code here:
        jMenu2.setForeground(Color.decode("#f5f3f1"));
    }//GEN-LAST:event_MouseExitedMenu2

    private void MouseExitedMenu3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseExitedMenu3
        // TODO add your handling code here:
        jMenu3.setForeground(Color.decode("#f5f3f1"));
    }//GEN-LAST:event_MouseExitedMenu3

    private void MouseExitedMenu4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseExitedMenu4
        // TODO add your handling code here:
        jMenu4.setForeground(Color.decode("#f5f3f1"));
    }//GEN-LAST:event_MouseExitedMenu4

    private void UsuariosClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosClick
        // TODO add your handling code here:
        //Se crea el objeto
        Usuarios UsuarioHijo = new Usuarios();
        //se añade al jDesktopPane
        jDesktopPane1.add(UsuarioHijo);
        //se muestra en pantalla
        UsuarioHijo.show();
        try {
            UsuarioHijo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UsuariosClick

    private void PerfilClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilClick
        // TODO add your handling code here:
        //Se crea el objeto
        Perfil PerfilHijo = new Perfil();
        //se añade al jDesktopPane
        jDesktopPane1.add(PerfilHijo);
        //se muestra en pantalla
        PerfilHijo.show();
        try {
            PerfilHijo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PerfilClick

    private void RolesClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolesClick
        // TODO add your handling code here:
        //Se crea el objeto
        Roles RolesHijo = new Roles();
        //se añade al jDesktopPane
        jDesktopPane1.add(RolesHijo);
        //se muestra en pantalla
        RolesHijo.show();
        try {
            RolesHijo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RolesClick

    private void InformesClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformesClick
        // TODO add your handling code here:
        //Se crea el objeto
        Informes InformesHijo = new Informes();
        //se añade al jDesktopPane
        jDesktopPane1.add(InformesHijo);
        //se muestra en pantalla
        InformesHijo.show();
        try {
            InformesHijo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InformesClick

    private void PlantillasClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantillasClick
        // TODO add your handling code here:
        //Se crea el objeto
        InformesPlantillas PlantillasHijo = new InformesPlantillas();
        //se añade al jDesktopPane
        jDesktopPane1.add(PlantillasHijo);
        //se muestra en pantalla
        PlantillasHijo.show();
        try {
            PlantillasHijo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PlantillasClick

    private void ModificarVehiculoClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarVehiculoClick
        // TODO add your handling code here:
        //Se crea el objeto
        ModificarVehiculo Hijo = new ModificarVehiculo();
        //se añade al jDesktopPane
        jDesktopPane1.add(Hijo);
        //se muestra en pantalla
        Hijo.show();
        try {
            Hijo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ModificarVehiculoClick

    private void CrearVehiculoClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearVehiculoClick
        // TODO add your handling code here:
        //Se crea el objeto
        CrearVehiculo Hijo = new CrearVehiculo();
        //se añade al jDesktopPane
        jDesktopPane1.add(Hijo);
        //se muestra en pantalla
        Hijo.show();
        try {
            Hijo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CrearVehiculoClick

    private void VehiculoPlantillasClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehiculoPlantillasClick
        // TODO add your handling code here:
        PlantillasVehiculo Hijo = new PlantillasVehiculo();
        //se añade al jDesktopPane
        jDesktopPane1.add(Hijo);
        //se muestra en pantalla
        Hijo.show();
        try {
            Hijo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VehiculoPlantillasClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
